[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cov"
description = "cov"
requires-python = ">=3.11"
version = "0.1.0"

[tool.coverage.run]
parallel = true
source = ["cov"]
